services:
  postgres:
    image: postgres:17
    container_name: lokhari-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  7ew8wLlHQJ4reZnowv7vUeXoVs9yQe7KPkXGjUBrq8PqgHCgOem8Wmth8u3oHou3
      POSTGRES_DB: lokhari

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lokhari-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend

    container_name: lokhari-backend

    depends_on:
      - postgres
      - redis

    env_file:
      - ./backend/.env

    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: lokhari-frontend

    depends_on:
      - backend

    ports:
      - "3000:3000"

volumes:
  postgres_data:
  redis_data: